name = "FastLocalCorrelationCoefficients"
uuid = "a52d4850-34f0-40c4-bafd-3adb601f862f"
authors = ["Nikos Pitsianis <nikos@cs.duke.edu> and contributors"]
version = "0.1.0"

[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
PaddedViews = "5432bcbf-9aad-5242-b902-cca2824c8663"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
